name: Daily DSA Problem

on:
  schedule:
    # Runs every day at 15:30 UTC
    # 15:30 UTC = 21:00 (9 PM) IST (UTC+5:30)
    - cron: "30 15 * * *"
  workflow_dispatch: {} # allow manual trigger from GitHub UI

jobs:
  send-dsa-problem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run daily script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node src/sendDaily.js
