name: Daily DSA Problem

permissions:
  contents: write

on:
  schedule:
    - cron: "30 15 * * *"   # 9:00 PM IST
  workflow_dispatch: {}

jobs:
  send-dsa-problem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run daily script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node src/sendDaily.js

      - name: Commit updated progress.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add progress.json
          git commit -m "Update progress [skip ci]" || echo "No changes to commit"
          git push
